Repository U2DJ2/moim-today, pull requests merged in 2024-05, with the labels that each got.

#68 [FEAT] 스케줄 조회 및 시간표 중복 예외 처리
  backend/src/main/java/moim_today/application/schedule/ScheduleService.java
  backend/src/main/java/moim_today/application/schedule/ScheduleServiceImpl.java
  backend/src/main/java/moim_today/domain/schedule/Schedule.java
  backend/src/main/java/moim_today/dto/schedule/ScheduleResponse.java
  backend/src/main/java/moim_today/global/constant/TimeConstant.java
  backend/src/main/java/moim_today/implement/schedule/ScheduleAppender.java
  backend/src/main/java/moim_today/implement/schedule/ScheduleFinder.java
  backend/src/main/java/moim_today/persistence/repository/schedule/ScheduleJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/ScheduleRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/ScheduleRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
  backend/src/test/java/moim_today/domain/schedule/ScheduleTest.java
  backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
  backend/src/test/java/moim_today/implement/schedule/ScheduleAppenderTest.java
  backend/src/test/java/moim_today/implement/schedule/ScheduleFinderTest.java
  backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java
Labels: feat⚙️

#75 [BE] feat : CORS 설정
  backend/src/main/java/moim_today/global/config/WebConfig.java
Labels: feat⚙️

#73 [BE] 대학교 크롤링 리팩토링 및 문서화 작성
  backend/src/main/java/moim_today/application/department/DepartmentService.java
  backend/src/main/java/moim_today/application/department/DepartmentServiceImpl.java
  backend/src/main/java/moim_today/application/university/UniversityService.java
  backend/src/main/java/moim_today/application/university/UniversityServiceImpl.java
  backend/src/main/java/moim_today/domain/department/Department.java
  backend/src/main/java/moim_today/domain/university/ExtractUniversity.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/global/constant/DepartmentConstant.java
  backend/src/main/java/moim_today/global/constant/UniversityConstant.java
  backend/src/main/java/moim_today/implement/department/DepartmentAppender.java
  backend/src/main/java/moim_today/implement/department/DepartmentFetcher.java
  backend/src/main/java/moim_today/implement/department/DepartmentFinder.java
  backend/src/main/java/moim_today/implement/university/UniversityAppender.java
  backend/src/main/java/moim_today/implement/university/UniversityFinder.java
  backend/src/main/java/moim_today/implement/university/UniversityUpdater.java
  backend/src/main/java/moim_today/persistence/entity/university/UniversityJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/department/DepartmentRepository.java
  backend/src/main/java/moim_today/persistence/repository/department/DepartmentRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/university/UniversityRepository.java
  backend/src/main/java/moim_today/persistence/repository/university/UniversityRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/department/DepartmentController.java
  backend/src/main/java/moim_today/presentation/university/UniversityController.java
  backend/src/test/java/moim_today/fake_class/department/FakeDepartmentService.java
  backend/src/test/java/moim_today/fake_class/university/FakeUniversityService.java
  backend/src/test/java/moim_today/implement/department/DepartmentAppenderTest.java
  backend/src/test/java/moim_today/implement/department/DepartmentFinderTest.java
  backend/src/test/java/moim_today/implement/university/UniversityFinderTest.java
  backend/src/test/java/moim_today/persistence/entity/certification_token/PasswordCertificationJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/department/DepartmentControllerTest.java
  backend/src/test/java/moim_today/presentation/university/UniversityControllerTest.java
  backend/src/test/java/moim_today/util/TestConstant.java
Labels: refactor

#90 [BE] refactor : 로그인 유지 여부 추가
  backend/src/main/java/moim_today/domain/member/MemberSession.java
  backend/src/main/java/moim_today/dto/auth/MemberLoginRequest.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/implement/member/AuthManager.java
  backend/src/test/java/moim_today/implement/member/AuthManagerTest.java
  backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java
Labels: refactor

#88 [BE] 스케줄 색상 추가
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/application/schedule/ScheduleServiceImpl.java
  backend/src/main/java/moim_today/domain/schedule/Schedule.java
  backend/src/main/java/moim_today/domain/schedule/TimeTableProcessor.java
  backend/src/main/java/moim_today/domain/schedule/enums/ColorHex.java
  backend/src/main/java/moim_today/dto/schedule/ScheduleCreateRequest.java
  backend/src/main/java/moim_today/dto/schedule/TimeTableRequest.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/global/constant/exception/ScheduleExceptionConstant.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleAppender.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleFinder.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleManager.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleRemover.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleUpdater.java
  backend/src/main/java/moim_today/implement/schedule/schedule_color/ScheduleColorAppender.java
  backend/src/main/java/moim_today/implement/schedule/schedule_color/ScheduleColorFinder.java
  backend/src/main/java/moim_today/implement/schedule/schedule_color/ScheduleColorManager.java
  backend/src/main/java/moim_today/implement/schedule/schedule_color/ScheduleColorUpdater.java
  backend/src/main/java/moim_today/persistence/entity/schedule/schedule/ScheduleJpaEntity.java
  backend/src/main/java/moim_today/persistence/entity/schedule/schedule_color/ScheduleColorJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule_color/ScheduleColorJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule_color/ScheduleColorRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule_color/ScheduleColorRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
  backend/src/test/java/moim_today/domain/schedule/ScheduleTest.java
  backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleAppenderTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleFinderTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleRemoverTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleUpdaterTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule_color/ScheduleColorAppenderTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule_color/ScheduleColorFinderTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule_color/ScheduleColorManagerTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule_color/ScheduleColorUpdaterTest.java
  backend/src/test/java/moim_today/persistence/entity/schedule/ScheduleJpaEntityTest.java
  backend/src/test/java/moim_today/persistence/entity/schedule/schedule_color/ScheduleColorJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java
  backend/src/test/java/moim_today/util/ImplementTest.java
Labels: feat⚙️

#95 [BE] feat : RestTemplate CORS 설정 추가
  backend/src/main/java/moim_today/global/config/CorsInterceptor.java
  backend/src/main/java/moim_today/global/config/RestTemplateConfig.java
Labels: feat⚙️

#99 [BE] feat : CORS header 설정 추가
  backend/src/main/java/moim_today/global/config/WebConfig.java
Labels: feat⚙️

#93 [BE] Enum 클래스 문서화 자동화
  backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java
  backend/src/test/java/moim_today/util/EnumDocsUtils.java
Labels: refactor

#102 [BE] 미팅 생성
  backend/src/main/java/moim_today/application/meeting/MeetingService.java
  backend/src/main/java/moim_today/application/meeting/MeetingServiceImpl.java
  backend/src/main/java/moim_today/domain/meeting/Meeting.java
  backend/src/main/java/moim_today/domain/meeting/enums/MeetingCategory.java
  backend/src/main/java/moim_today/dto/meeting/MeetingCreateRequest.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimDateResponse.java
  backend/src/main/java/moim_today/dto/schedule/ScheduleResponse.java
  backend/src/main/java/moim_today/global/constant/exception/MeetingExceptionConstant.java
  backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingAppender.java
  backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingFinder.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingAppender.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleAppender.java
  backend/src/main/java/moim_today/persistence/entity/meeting/joined_meeting/JoinedMeetingJpaEntity.java
  backend/src/main/java/moim_today/persistence/entity/meeting/meeting/MeetingJpaEntity.java
  backend/src/main/java/moim_today/persistence/entity/schedule/schedule/ScheduleJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/meeting/MeetingController.java
  backend/src/test/java/moim_today/fake_class/meeting/FakeMeetingService.java
  backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
  backend/src/test/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingAppenderTest.java
  backend/src/test/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingFinderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingAppenderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleAppenderTest.java
  backend/src/test/java/moim_today/presentation/meeting/MeetingControllerTest.java
  backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java
  backend/src/test/java/moim_today/util/TestConstant.java
Labels: feat⚙️, refactor

#104 [BE] 다른 회원의 캘린더 조회
  backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
  backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java
Labels: feat⚙️

#105 [BE] 모임 멤버 탭 관련 기능 추가
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimMemberDeleteRequest.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimMemberResponse.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimMemberTabResponse.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/global/constant/MemberConstant.java
  backend/src/main/java/moim_today/global/constant/exception/JoinedMoimExceptionConstant.java
  backend/src/main/java/moim_today/global/constant/exception/MeetingCommentExceptionConstant.java
  backend/src/main/java/moim_today/global/constant/exception/MemberExceptionConstant.java
  backend/src/main/java/moim_today/implement/department/DepartmentAppender.java
  backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingRemover.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingFinder.java
  backend/src/main/java/moim_today/implement/meeting/meeting_comment/MeetingCommentUpdater.java
  backend/src/main/java/moim_today/implement/member/MemberFinder.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimManager.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimRemover.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimAppender.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleRemover.java
  backend/src/main/java/moim_today/implement/todo/TodoRemover.java
  backend/src/main/java/moim_today/persistence/entity/meeting/meeting_comment/MeetingCommentJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/member/MemberJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/member/MemberRepository.java
  backend/src/main/java/moim_today/persistence/repository/member/MemberRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoRepository.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingAppenderTest.java
  backend/src/test/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingRemoverTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingAppenderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting_comment/MeetingCommentUpdaterTest.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimRemoverTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimUpdaterTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleRemoverTest.java
  backend/src/test/java/moim_today/implement/todo/TodoRemoverTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
  backend/src/test/java/moim_today/presentation/university/UniversityControllerTest.java
  backend/src/test/java/moim_today/util/ImplementTest.java
  backend/src/test/java/moim_today/util/TestConstant.java
Labels: feat⚙️

#107 [BE] 파일 기능 문서화
  backend/src/main/java/moim_today/presentation/file/FileController.java
  backend/src/test/java/moim_today/fake_class/file/FakeFileService.java
  backend/src/test/java/moim_today/presentation/file/FileControllerTest.java
Labels: documentation

#112 [BE] 모임내 가용시간 계산
  backend/src/main/java/moim_today/application/schedule/ScheduleService.java
  backend/src/main/java/moim_today/application/schedule/ScheduleServiceImpl.java
  backend/src/main/java/moim_today/domain/member/Member.java
  backend/src/main/java/moim_today/domain/schedule/AvailableTime.java
  backend/src/main/java/moim_today/domain/schedule/ScheduleLocalDate.java
  backend/src/main/java/moim_today/domain/schedule/ScheduleYearMonth.java
  backend/src/main/java/moim_today/domain/schedule/enums/AvailableColorHex.java
  backend/src/main/java/moim_today/dto/member/MemberSimpleResponse.java
  backend/src/main/java/moim_today/dto/schedule/AvailableTimeResponse.java
  backend/src/main/java/moim_today/dto/schedule/MoimScheduleResponse.java
  backend/src/main/java/moim_today/dto/schedule/ScheduleCreateRequest.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleFinder.java
  backend/src/main/java/moim_today/persistence/entity/schedule/schedule/ScheduleJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
  backend/src/test/java/moim_today/domain/member/MemberTest.java
  backend/src/test/java/moim_today/domain/schedule/AvailableTimeTest.java
  backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleFinderTest.java
  backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java
  backend/src/test/java/moim_today/util/TestConstant.java
Labels: feat⚙️

#120 [BE] refactor : 인증 메일 UI 수정
  backend/src/main/resources/templates/certificationPage.html
  backend/src/main/resources/templates/emailCertificationMail.html
Labels: refactor

#121 [BE] 다가오는/이전 미팅 조회
  backend/src/main/java/moim_today/application/meeting/MeetingService.java
  backend/src/main/java/moim_today/application/meeting/MeetingServiceImpl.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/domain/meeting/Meeting.java
  backend/src/main/java/moim_today/domain/meeting/enums/MeetingStatus.java
  backend/src/main/java/moim_today/domain/schedule/enums/ColorHex.java
  backend/src/main/java/moim_today/dto/meeting/MeetingSimpleResponse.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/meeting/MeetingController.java
  backend/src/test/java/moim_today/fake_class/meeting/FakeMeetingService.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingFinderTest.java
  backend/src/test/java/moim_today/presentation/meeting/MeetingControllerTest.java
  backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java
Labels: feat⚙️

#124 [FEAT] 모임 카테고리별, 정렬 순 반환
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/application/moim/moim_notice/MoimNoticeServiceImpl.java
  backend/src/main/java/moim_today/domain/moim/MoimSortedFilter.java
  backend/src/main/java/moim_today/domain/moim/enums/MoimCategory.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimFilterRequest.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimSimpleResponse.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
  backend/src/test/java/moim_today/util/TestConstant.java
Labels: feat⚙️, refactor

#122 [FEAT] 모임 조회시 조회수 증가
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/domain/moim/ViewedMoim.java
  backend/src/main/java/moim_today/domain/moim/ViewedMoimsCookie.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/global/constant/MoimConstant.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/global/constant/exception/MoimExceptionConstant.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimUpdater.java
  backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/domain/moim/ViewedMoimTest.java
  backend/src/test/java/moim_today/domain/moim/ViewedMoimsCookieTest.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimUpdaterTest.java
  backend/src/test/java/moim_today/persistence/entity/moim/moim/MoimJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
  backend/src/test/java/moim_today/util/ControllerTest.java
  backend/src/test/java/moim_today/util/SerializingObjectMapper.java
Labels: feat⚙️, refactor

#127 [FEAT] 모임 검색
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimCreateRequest.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/global/constant/SymbolConstant.java
  backend/src/main/java/moim_today/global/constant/exception/MoimExceptionConstant.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/persistence/entity/invitation_link/InvitationLinkJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/invitation_link/InvitationLinkJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/invitation_link/InvitationLinkRepository.java
  backend/src/main/java/moim_today/persistence/repository/invitation_link/InvitationLinkRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/dto/moim/moim/MoimCreateRequestTest.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: feat⚙️

#128 [BE] 모임 생성시 ID값 반환, Get요청 파라미터 변경
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimFilterRequest.java
  backend/src/main/java/moim_today/dto/moim/moim/MoimIdResponse.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: feat⚙️

#130 [BE] 모임의 투두 관련 기능 구현
  backend/src/main/java/moim_today/application/moim/moim_notice/MoimNoticeServiceImpl.java
  backend/src/main/java/moim_today/application/todo/TodoService.java
  backend/src/main/java/moim_today/application/todo/TodoServiceImpl.java
  backend/src/main/java/moim_today/domain/moim/ViewedMoim.java
  backend/src/main/java/moim_today/domain/moim/ViewedMoimsCookie.java
  backend/src/main/java/moim_today/domain/todo/TodoLocalDateTime.java
  backend/src/main/java/moim_today/dto/todo/MemberTodoResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoCreateRequest.java
  backend/src/main/java/moim_today/dto/todo/TodoCreateResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoDetailResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoRemoveRequest.java
  backend/src/main/java/moim_today/dto/todo/TodoResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoUpdateRequest.java
  backend/src/main/java/moim_today/dto/todo/TodoUpdateResponse.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/global/constant/TimeConstant.java
  backend/src/main/java/moim_today/global/constant/exception/TodoExceptionConstant.java
  backend/src/main/java/moim_today/global/error/ApiRestControllerAdvice.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimManager.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/implement/todo/TodoAppender.java
  backend/src/main/java/moim_today/implement/todo/TodoFinder.java
  backend/src/main/java/moim_today/implement/todo/TodoManager.java
  backend/src/main/java/moim_today/implement/todo/TodoRemover.java
  backend/src/main/java/moim_today/implement/todo/TodoUpdater.java
  backend/src/main/java/moim_today/persistence/entity/todo/TodoJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoRepository.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/todo/TodoController.java
  backend/src/test/java/moim_today/domain/moim/ViewedMoimTest.java
  backend/src/test/java/moim_today/fake_class/todo/FakeTodoService.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimAppenderTest.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
  backend/src/test/java/moim_today/implement/todo/TodoAppenderTest.java
  backend/src/test/java/moim_today/implement/todo/TodoFinderTest.java
  backend/src/test/java/moim_today/implement/todo/TodoManagerTest.java
  backend/src/test/java/moim_today/implement/todo/TodoRemoverTest.java
  backend/src/test/java/moim_today/implement/todo/TodoUpdaterTest.java
  backend/src/test/java/moim_today/persistence/entity/todo/TodoJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java
  backend/src/test/java/moim_today/presentation/todo/TodoControllerTest.java
  backend/src/test/java/moim_today/util/TestConstant.java
Labels: feat⚙️

#131 [BE] 모임 리스트 조회시 전체 카테고리 추가
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/dto/moim/moim/enums/MoimCategoryDto.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: refactor

#134 [BE] 모임 생성자 프로필 조회
  backend/src/main/java/moim_today/application/member/MemberService.java
  backend/src/main/java/moim_today/application/member/MemberServiceImpl.java
  backend/src/main/java/moim_today/dto/member/MemberSimpleResponse.java
  backend/src/main/java/moim_today/dto/schedule/AvailableTimeInMoimResponse.java
  backend/src/main/java/moim_today/global/constant/exception/MemberExceptionConstant.java
  backend/src/main/java/moim_today/implement/member/MemberFinder.java
  backend/src/main/java/moim_today/persistence/repository/member/MemberRepository.java
  backend/src/main/java/moim_today/persistence/repository/member/MemberRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/member/MemberController.java
  backend/src/test/java/moim_today/fake_class/member/FakeMemberService.java
  backend/src/test/java/moim_today/implement/member/MemberFinderTest.java
  backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: feat⚙️

#136 [BE] hotfix : 멤버가 모임에 참여할 때 모임의 currentCount 도 검사하도록 수정
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/persistence/entity/moim/moim/MoimJpaEntityTest.java
Labels: feat⚙️

#135 [BE] 투두 기능 수정 및 자신의 투두 조회하는 기능 추가
  backend/src/main/java/moim_today/application/todo/TodoService.java
  backend/src/main/java/moim_today/application/todo/TodoServiceImpl.java
  backend/src/main/java/moim_today/domain/todo/TodoLocalDateTime.java
  backend/src/main/java/moim_today/domain/todo/enums/TodoProgress.java
  backend/src/main/java/moim_today/dto/auth/MemberSignUpRequest.java
  backend/src/main/java/moim_today/dto/todo/MemberMoimTodoResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoCreateRequest.java
  backend/src/main/java/moim_today/dto/todo/TodoDetailResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoUpdateRequest.java
  backend/src/main/java/moim_today/dto/todo/TodoUpdateResponse.java
  backend/src/main/java/moim_today/global/constant/exception/TodoExceptionConstant.java
  backend/src/main/java/moim_today/global/error/ApiRestControllerAdvice.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimManager.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/implement/todo/TodoAppender.java
  backend/src/main/java/moim_today/implement/todo/TodoFinder.java
  backend/src/main/java/moim_today/implement/todo/TodoManager.java
  backend/src/main/java/moim_today/persistence/entity/todo/TodoJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoRepository.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/todo/TodoController.java
  backend/src/test/java/moim_today/fake_class/todo/FakeTodoService.java
  backend/src/test/java/moim_today/implement/todo/TodoAppenderTest.java
  backend/src/test/java/moim_today/implement/todo/TodoFinderTest.java
  backend/src/test/java/moim_today/implement/todo/TodoManagerTest.java
  backend/src/test/java/moim_today/implement/todo/TodoUpdaterTest.java
  backend/src/test/java/moim_today/persistence/entity/todo/TodoJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/meeting/meeting/MeetingControllerTest.java
  backend/src/test/java/moim_today/presentation/todo/TodoControllerTest.java
Labels: feat⚙️

#138 [BE] 미팅 삭제
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingService.java
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
  backend/src/main/java/moim_today/domain/schedule/enums/ColorHex.java
  backend/src/main/java/moim_today/global/constant/exception/MeetingExceptionConstant.java
  backend/src/main/java/moim_today/implement/mail/MailScheduler.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingRemover.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/meeting/meeting/MeetingController.java
  backend/src/main/resources/templates/certificationPage.html
  backend/src/test/java/moim_today/fake_class/meeting/meeting/FakeMeetingService.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingRemoverTest.java
  backend/src/test/java/moim_today/presentation/meeting/meeting/MeetingControllerTest.java
Labels: feat⚙️

#140 [BE] fix : 모임의 멤버 조회할 때 moimId를 이용한 조건을 추가
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/implement/member/MemberFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/persistence/entity/moim/joined_moim/JoinedMoimJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/member/MemberRepository.java
  backend/src/main/java/moim_today/persistence/repository/member/MemberRepositoryImpl.java
  backend/src/test/java/moim_today/implement/member/MemberFinderTest.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
Labels: fix🔧

#144 [BE] 모임 공지 리스트 조회시 잘못된 캐시값 문제 수정
  backend/src/main/java/moim_today/application/moim/moim_notice/MoimNoticeServiceImpl.java
  backend/src/main/java/moim_today/implement/moim/moim_notice/MoimNoticeAppender.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim_notice/MoimNoticeAppenderTest.java
Labels: fix🔧

#152 [BE] 미팅 생성시 정보 반환하도록 수정
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingService.java
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
  backend/src/main/java/moim_today/dto/meeting/MeetingCreateResponse.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingAppender.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
  backend/src/main/java/moim_today/presentation/meeting/meeting/MeetingController.java
  backend/src/test/java/moim_today/fake_class/meeting/meeting/FakeMeetingService.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingAppenderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
  backend/src/test/java/moim_today/presentation/meeting/meeting/MeetingControllerTest.java
Labels: refactor

#156 [BE] 회원 세션 유효 검증
  backend/src/main/java/moim_today/application/auth/AuthService.java
  backend/src/main/java/moim_today/application/auth/AuthServiceImpl.java
  backend/src/main/java/moim_today/domain/member/MemberSession.java
  backend/src/main/java/moim_today/dto/auth/MemberSessionValidateResponse.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/presentation/auth/AuthController.java
  backend/src/test/java/moim_today/fake_class/auth/FakeAuthService.java
  backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java
Labels: feat⚙️

#157 [BE] refactor : 세션 인증 API URL 변경
  backend/src/main/java/moim_today/presentation/auth/AuthController.java
  backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java
Labels: refactor

#162 [BE] 미팅 정보 조회 쿼리 오류 수정
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
Labels: fix🔧

#163 [BE] 모임 참여시 미팅 정보 저장하도록 수정
  backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingAppender.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
Labels: fix🔧

#168 [BE] 미팅 댓글 CRUD
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingService.java
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
  backend/src/main/java/moim_today/application/meeting/meeting_comment/MeetingCommentService.java
  backend/src/main/java/moim_today/application/meeting/meeting_comment/MeetingCommentServiceImpl.java
  backend/src/main/java/moim_today/dto/meeting/MeetingCreateResponse.java
  backend/src/main/java/moim_today/dto/meeting/meeting/MeetingCreateRequest.java
  backend/src/main/java/moim_today/dto/meeting/meeting/MeetingDetailResponse.java
  backend/src/main/java/moim_today/dto/meeting/meeting/MeetingSimpleDao.java
  backend/src/main/java/moim_today/dto/meeting/meeting/MeetingSimpleResponse.java
  backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentCreateRequest.java
  backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentDeleteRequest.java
  backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentResponse.java
  backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentUpdateRequest.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/global/constant/exception/MeetingExceptionConstant.java
  backend/src/main/java/moim_today/global/response/CollectionResponse.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingFinder.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
  backend/src/main/java/moim_today/implement/meeting/meeting_comment/MeetingCommentAppender.java
  backend/src/main/java/moim_today/implement/meeting/meeting_comment/MeetingCommentFinder.java
  backend/src/main/java/moim_today/implement/meeting/meeting_comment/MeetingCommentRemover.java
  backend/src/main/java/moim_today/implement/meeting/meeting_comment/MeetingCommentUpdater.java
  backend/src/main/java/moim_today/persistence/entity/meeting/meeting_comment/MeetingCommentJpaEntity.java
  backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/department/DepartmentController.java
  backend/src/main/java/moim_today/presentation/meeting/meeting/MeetingController.java
  backend/src/main/java/moim_today/presentation/meeting/meeting_comment/MeetingCommentController.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
  backend/src/main/java/moim_today/presentation/todo/TodoController.java
  backend/src/main/java/moim_today/presentation/university/UniversityController.java
  backend/src/test/java/moim_today/fake_class/meeting/meeting/FakeMeetingService.java
  backend/src/test/java/moim_today/fake_class/meeting/meeting_comment/FakeMeetingCommentService.java
  backend/src/test/java/moim_today/global/response/CollectionResponseTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingFinderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting_comment/MeetingCommentAppenderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting_comment/MeetingCommentFinderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting_comment/MeetingCommentRemoverTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting_comment/MeetingCommentUpdaterTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimRemoverTest.java
  backend/src/test/java/moim_today/persistence/entity/meeting/meeting_comment/MeetingCommentJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/meeting/meeting/MeetingControllerTest.java
  backend/src/test/java/moim_today/presentation/meeting/meeting_comment/MeetingCommentControllerTest.java
  backend/src/test/java/moim_today/util/TestConstant.java
Labels: feat⚙️

#171 [BE] 모임 리스트 조회, 모임 검색시 같은 대학 모임만 조회
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingService.java
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimAppender.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/meeting/meeting/MeetingController.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/meeting/meeting/FakeMeetingService.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
Labels: feat⚙️

#173 [FEAT] 자신이 참여한 모임들을 완료 여부에 따라 조회하고 카드 정보로 반환할 수 있다
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/dto/moim/moim_notice/MoimNoticeCreateRequest.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: feat⚙️

#172 [BE] 이메일 수신 차단 여부 설정
  backend/src/main/java/moim_today/application/email_subscribe/EmailSubscribeService.java
  backend/src/main/java/moim_today/application/email_subscribe/EmailSubscribeServiceImpl.java
  backend/src/main/java/moim_today/dto/mail/EmailSubscribeRequest.java
  backend/src/main/java/moim_today/dto/mail/EmailSubscriptionResponse.java
  backend/src/main/java/moim_today/global/constant/exception/MailExceptionConstant.java
  backend/src/main/java/moim_today/implement/email_subscribe/EmailSubscribeAppender.java
  backend/src/main/java/moim_today/implement/email_subscribe/EmailSubscribeUpdater.java
  backend/src/main/java/moim_today/implement/email_subscribe/EmailSubscriptionFinder.java
  backend/src/main/java/moim_today/implement/mail/MailScheduler.java
  backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingUpdater.java
  backend/src/main/java/moim_today/implement/member/AuthManager.java
  backend/src/main/java/moim_today/persistence/entity/email_subscribe/EmailSubscribeJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/email_subscribe/EmailSubscribeJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/email_subscribe/EmailSubscribeRepository.java
  backend/src/main/java/moim_today/persistence/repository/email_subscribe/EmailSubscribeRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/email_subscribe/EmailSubscribeController.java
  backend/src/test/java/moim_today/fake_class/email_subscribe/FakeEmailSubscribeService.java
  backend/src/test/java/moim_today/implement/email_subscribe/EmailSubscribeAppenderTest.java
  backend/src/test/java/moim_today/implement/email_subscribe/EmailSubscribeUpdaterTest.java
  backend/src/test/java/moim_today/implement/email_subscribe/EmailSubscriptionFinderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingFinderTest.java
  backend/src/test/java/moim_today/implement/member/AuthManagerTest.java
  backend/src/test/java/moim_today/persistence/entity/email_subscribe/EmailSubscribeJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/email_subscribe/EmailSubscribeControllerTest.java
  backend/src/test/java/moim_today/util/ImplementTest.java
Labels: feat⚙️

#182 [BE] fix : calendar 오타 수정
  backend/src/main/java/moim_today/dto/schedule/AvailableTimeForMemberResponse.java
  backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
  backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java
Labels: fix🔧

#183 [BE] 회원이 참여한 모임/생성한 모임 리스트 조회시 정렬 적용 및 No Offset을 이용한 페이징 처리
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim_notice/MoimNoticeRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: feat⚙️, refactor

#185 [BE] 멤버가 모임에서 나갈시, 모임의 현재 인원 수정 로직 추가 및 리팩토링
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimAppender.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimUpdater.java
  backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimAppenderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimUpdaterTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: refactor, fix🔧

#186 [BE] 모임 공지 리스트 반환시 년/월/일/요일 반환
  backend/src/main/java/moim_today/dto/moim/moim_notice/MoimNoticeSimpleResponse.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimNoticeService.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: feat⚙️

#187 [BE] 투두를 조회했을 때 데이터 포맷과 정렬 수정
  backend/src/main/java/moim_today/application/todo/TodoService.java
  backend/src/main/java/moim_today/application/todo/TodoServiceImpl.java
  backend/src/main/java/moim_today/domain/todo/TodoContents.java
  backend/src/main/java/moim_today/domain/todo/TodoGroupByDate.java
  backend/src/main/java/moim_today/dto/todo/MemberMoimTodoResponse.java
  backend/src/main/java/moim_today/dto/todo/MemberTodoResponse.java
  backend/src/main/java/moim_today/dto/todo/TodoProgressUpdateRequest.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
  backend/src/main/java/moim_today/implement/todo/TodoFinder.java
  backend/src/main/java/moim_today/implement/todo/TodoManager.java
  backend/src/main/java/moim_today/implement/todo/TodoUpdater.java
  backend/src/main/java/moim_today/persistence/entity/todo/TodoJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/todo/TodoRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/todo/TodoController.java
  backend/src/test/java/moim_today/domain/todo/TodoGroupByDateTest.java
  backend/src/test/java/moim_today/fake_class/todo/FakeTodoService.java
  backend/src/test/java/moim_today/implement/todo/TodoManagerTest.java
  backend/src/test/java/moim_today/presentation/todo/TodoControllerTest.java
Labels: feat⚙️, fix🔧

#191 [FE] feat : 주요 기능 관련 오류 수정 및 모임디테일 페이지, 미팅 카테고리 api 연결"
  frontend/moim_front/src/api/moim.js
  frontend/moim_front/src/api/schedule.js
  frontend/moim_front/src/assets/ManageLayout/SidebarElement/Icon/index.jsx
  frontend/moim_front/src/assets/ManageLayout/SidebarElement/index.jsx
  frontend/moim_front/src/assets/ManageLayout/SidebarElement/navigation/index.jsx
  frontend/moim_front/src/assets/ManageLayout/index.jsx
  frontend/moim_front/src/components/AuthLeft/index.jsx
  frontend/moim_front/src/components/AuthRight/index.jsx
  frontend/moim_front/src/components/Calendar/PersonalCalendar.jsx
  frontend/moim_front/src/components/CreationModal/index.jsx
  frontend/moim_front/src/components/DatePicker/Range.jsx
  frontend/moim_front/src/components/DetailedLeft/index.jsx
  frontend/moim_front/src/components/Dropdown/Profile.jsx
  frontend/moim_front/src/components/Dropdown/Search.jsx
  frontend/moim_front/src/components/Dropdown/Simple.jsx
  frontend/moim_front/src/components/MoimLayout/index.jsx
  frontend/moim_front/src/components/PageContainer/MoimContainer/index.jsx
  frontend/moim_front/src/main.css
  frontend/moim_front/src/main.jsx
  frontend/moim_front/src/pages/Home/CardContainer/index.jsx
  frontend/moim_front/src/pages/Home/Home.jsx
  frontend/moim_front/src/pages/Home/MoimCreation.jsx
  frontend/moim_front/src/pages/Login/index.jsx
  frontend/moim_front/src/pages/Manage/OverviewSection.jsx
  frontend/moim_front/src/pages/Manage/ProfileSection.jsx
  frontend/moim_front/src/pages/ManageMoimPage/index.jsx
  frontend/moim_front/src/pages/ManageProfilePage/index.jsx
  frontend/moim_front/src/pages/MeetingDetailPage/index.jsx
  frontend/moim_front/src/pages/MoimDetailPage/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/AvailableTime/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/CardComponent/CardBtn/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/CardComponent/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/Member/MemberInfo/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/Member/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/MoimHome/MeetingCreation/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/MoimHome/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/ToDo/index.jsx
  frontend/moim_front/src/pages/MoimJoinPage/index.jsx
  frontend/moim_front/src/pages/MoimMeetingPage/index.jsx
  frontend/moim_front/src/pages/RegisterPage/Personal/index.jsx
  frontend/moim_front/src/pages/RegisterPage/TimeTable/index.jsx
  frontend/moim_front/src/pages/RegisterPage/index.jsx
  frontend/moim_front/src/pages/Schedule/PersonalSection.jsx
  frontend/moim_front/src/pages/Schedule/index.jsx
  frontend/moim_front/src/router/index.jsx
Labels: feat⚙️, fix🔧

#193 [BE] 학과 추가 요청
  backend/src/main/java/moim_today/application/auth/AuthServiceImpl.java
  backend/src/main/java/moim_today/application/department/department/DepartmentService.java
  backend/src/main/java/moim_today/application/department/department/DepartmentServiceImpl.java
  backend/src/main/java/moim_today/application/department/request_department/RequestDepartmentService.java
  backend/src/main/java/moim_today/application/department/request_department/RequestDepartmentServiceImpl.java
  backend/src/main/java/moim_today/dto/department/AddDepartmentRequest.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/implement/department/department/DepartmentAppender.java
  backend/src/main/java/moim_today/implement/department/department/DepartmentFetcher.java
  backend/src/main/java/moim_today/implement/department/department/DepartmentFinder.java
  backend/src/main/java/moim_today/implement/department/request_department/RequestDepartmentAppender.java
  backend/src/main/java/moim_today/implement/member/MemberUpdater.java
  backend/src/main/java/moim_today/persistence/entity/department/request_deparment/RequestDepartmentJpaEntity.java
  backend/src/main/java/moim_today/persistence/repository/department/department/DepartmentJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/department/department/DepartmentRepository.java
  backend/src/main/java/moim_today/persistence/repository/department/department/DepartmentRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/department/request_department/RequestDepartmentJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/department/request_department/RequestDepartmentRepository.java
  backend/src/main/java/moim_today/persistence/repository/department/request_department/RequestDepartmentRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/department/department/DepartmentController.java
  backend/src/main/java/moim_today/presentation/department/request_department/RequestDepartmentController.java
  backend/src/test/java/moim_today/fake_class/department/department/FakeDepartmentService.java
  backend/src/test/java/moim_today/fake_class/department/request_department/FakeRequestDepartmentService.java
  backend/src/test/java/moim_today/implement/department/department/DepartmentAppenderTest.java
  backend/src/test/java/moim_today/implement/department/department/DepartmentFinderTest.java
  backend/src/test/java/moim_today/implement/department/request_department/RequestDepartmentAppenderTest.java
  backend/src/test/java/moim_today/presentation/department/department/DepartmentControllerTest.java
  backend/src/test/java/moim_today/presentation/department/request_department/RequestDepartmentControllerTest.java
  backend/src/test/java/moim_today/util/ImplementTest.java
Labels: feat⚙️

#194 [BE] 미팅 생성시 모임 기간 체크
  backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
  backend/src/main/java/moim_today/global/constant/exception/MeetingExceptionConstant.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
  backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
  backend/src/test/java/moim_today/persistence/entity/moim/moim/MoimJpaEntityTest.java
Labels: feat⚙️

#197 [BE] 날짜 검사를 매개변수로 받도록 수정
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/global/constant/exception/MoimExceptionConstant.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
  backend/src/test/java/moim_today/persistence/entity/moim/moim/MoimJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: fix🔧

#199 [BE] fix : 어드민 페이지 CORS 에러 수정
  backend/src/main/resources/static/admin-login.html
  backend/src/main/resources/static/js/get-members.js
  backend/src/main/resources/static/js/select-departments.js
  backend/src/main/resources/static/js/select-universities.js
  backend/src/main/resources/static/js/validate-admin.js
Labels: fix🔧

#200 [BE] fix : 어드민 페이지 CORS 에러 수정
  backend/src/main/resources/static/admin-login.html
  backend/src/main/resources/static/js/get-members.js
  backend/src/main/resources/static/js/select-departments.js
  backend/src/main/resources/static/js/select-universities.js
  backend/src/main/resources/static/js/validate-admin.js
Labels: fix🔧

#202 [BE] 댓글 개수, 회원 id 추가
  backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentCollectionResponse.java
  backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentResponse.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/meeting/meeting_comment/MeetingCommentController.java
  backend/src/test/java/moim_today/fake_class/meeting/meeting_comment/FakeMeetingCommentService.java
  backend/src/test/java/moim_today/presentation/meeting/meeting_comment/MeetingCommentControllerTest.java
Labels: refactor

#208 [BE] 회원 프로필 수정 필드 변경
  backend/src/main/java/moim_today/application/member/MemberService.java
  backend/src/main/java/moim_today/application/member/MemberServiceImpl.java
  backend/src/main/java/moim_today/dto/member/ProfileUpdateRequest.java
  backend/src/main/java/moim_today/implement/member/MemberUpdater.java
  backend/src/main/java/moim_today/persistence/entity/member/MemberJpaEntity.java
  backend/src/main/java/moim_today/presentation/member/MemberController.java
  backend/src/test/java/moim_today/fake_class/member/FakeMemberService.java
  backend/src/test/java/moim_today/implement/member/MemberUpdaterTest.java
  backend/src/test/java/moim_today/persistence/entity/member/MemberJpaEntityTest.java
  backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java
Labels: feat⚙️

#209 [BE] 정렬 및 페이징 처리 revert
  backend/src/main/java/moim_today/application/moim/moim/MoimService.java
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim_notice/MoimNoticeRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/moim/MoimController.java
  backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
  backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
  backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java
Labels: feat⚙️

#204 [BE] 학교별 학과 관리 - 어드민
  backend/src/main/java/moim_today/application/admin/department/AdminDepartmentService.java
  backend/src/main/java/moim_today/application/admin/department/AdminDepartmentServiceImpl.java
  backend/src/main/java/moim_today/application/department/request_department/RequestDepartmentService.java
  backend/src/main/java/moim_today/application/department/request_department/RequestDepartmentServiceImpl.java
  backend/src/main/java/moim_today/implement/department/request_department/RequestDepartmentFinder.java
  backend/src/main/java/moim_today/persistence/repository/department/request_department/RequestDepartmentRepository.java
  backend/src/main/java/moim_today/persistence/repository/department/request_department/RequestDepartmentRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/admin/AdminController.java
  backend/src/main/java/moim_today/presentation/admin/department/AdminDepartmentController.java
  backend/src/main/java/moim_today/presentation/department/request_department/RequestDepartmentController.java
  backend/src/test/java/moim_today/fake_class/admin/department/FakeAdminDepartmentService.java
  backend/src/test/java/moim_today/fake_class/department/request_department/FakeRequestDepartmentService.java
  backend/src/test/java/moim_today/implement/department/request_department/RequestDepartmentFinderTest.java
  backend/src/test/java/moim_today/presentation/admin/AdminDepartmentControllerTest.java
  backend/src/test/java/moim_today/presentation/department/request_department/RequestDepartmentControllerTest.java
Labels: feat⚙️

#215 [BE] 모임 멤버 참여시 카운트 증가 수정
  backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
  backend/src/main/java/moim_today/global/constant/NumberConstant.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
  backend/src/test/java/moim_today/presentation/meeting/joined_meeting/JoinedMeetingControllerTest.java
Labels: fix🔧

#217 [BE] 어드민 정적 파일 수정
  backend/src/main/resources/static/admin-login.html
  backend/src/main/resources/static/department-addition-inquiry.html
  backend/src/main/resources/static/department-management.html
  backend/src/main/resources/static/js/get-members.js
  backend/src/main/resources/static/js/select-departments.js
  backend/src/main/resources/static/js/select-universities.js
  backend/src/main/resources/static/js/validate-admin.js
  backend/src/main/resources/static/meeting-management.html
  backend/src/main/resources/static/member-management.html
  backend/src/main/resources/static/moim-management.html
  backend/src/main/resources/static/service-inquiry.html
Labels: refactor, fix🔧

#216 [BE] 모임, 미팅 생성/참여시 회원의 캘린더 관리
  backend/src/main/java/moim_today/application/meeting/joined_meeting/JoinedMeetingServiceImpl.java
  backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingAppender.java
  backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingUpdater.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingFinder.java
  backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
  backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleAppender.java
  backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleRemover.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
  backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepository.java
  backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepositoryImpl.java
  backend/src/test/java/moim_today/application/meeting/joined_meeting/JoinedMeetingServiceImplTest.java
  backend/src/test/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingAppenderTest.java
  backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
  backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleRemoverTest.java
Labels: feat⚙️

#218 [BE] 어드민 페이지 설정 변경
  backend/src/main/java/moim_today/application/admin/AdminService.java
  backend/src/main/java/moim_today/application/admin/AdminServiceImpl.java
  backend/src/main/java/moim_today/application/admin/auth/AdminAuthService.java
  backend/src/main/java/moim_today/application/admin/department/AdminDepartmentService.java
  backend/src/main/java/moim_today/application/admin/department/AdminDepartmentServiceImpl.java
  backend/src/main/java/moim_today/application/admin/member/AdminMemberService.java
  backend/src/main/java/moim_today/global/config/WebConfig.java
  backend/src/main/java/moim_today/global/constant/MemberSessionConstant.java
  backend/src/main/java/moim_today/global/constant/exception/SessionExceptionConstant.java
  backend/src/main/java/moim_today/global/interceptor/AdminLoginInterceptor.java
  backend/src/main/java/moim_today/presentation/admin/AdminController.java
  backend/src/main/java/moim_today/presentation/admin/auth/AdminAuthController.java
  backend/src/main/java/moim_today/presentation/admin/member/AdminMemberController.java
  backend/src/test/java/moim_today/fake_class/admin/department/FakeAdminDepartmentService.java
  backend/src/test/java/moim_today/presentation/admin/AdminDepartmentControllerTest.java
Labels: refactor

#220 [BE] 어드민 모임 관리
  backend/src/main/java/moim_today/application/admin/moim/AdminMoimService.java
  backend/src/main/java/moim_today/implement/mail/MailScheduler.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimJpaRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
  backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
  backend/src/main/java/moim_today/presentation/admin/moim/AdminMoimController.java
  backend/src/test/java/moim_today/application/admin/moim/AdminMoimServiceTest.java
Labels: feat⚙️
