Repository U2DJ2/moim-today, pull requests merged in 2024-03, with the labels that each got.

#4 [BE] 모니터링 의존성 추가
  backend/build.gradle
Labels: enhancement

#6 Feat/persistence setting
  backend/src/main/java/booki_today/domain/created_booki/BookiType.java
  backend/src/main/java/booki_today/domain/member/Gender.java
  backend/src/main/java/booki_today/domain/member/LoginType.java
  backend/src/main/java/booki_today/domain/participated_booki/ParticipatedStatus.java
  backend/src/main/java/booki_today/global/annotation/Association.java
  backend/src/main/java/booki_today/persistence/entity/created_booki/CreatedBookiJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/invitation_link/InvitationLinkJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/member/MemberJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/participated_booki/ParticipatedBookiJpaEntity.java
  backend/src/main/java/booki_today/persistence/repository/created_booki/CreatedBookiJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/created_booki/CreatedBookiRepository.java
  backend/src/main/java/booki_today/persistence/repository/created_booki/CreatedBookiRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/invitation_link/InvitationLinkJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/invitation_link/InvitationLinkRepository.java
  backend/src/main/java/booki_today/persistence/repository/invitation_link/InvitationLinkRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/member/MemberJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/member/MemberRepository.java
  backend/src/main/java/booki_today/persistence/repository/member/MemberRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/participated_booki/ParticipatedBookiJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/participated_booki/ParticipatedBookiRepository.java
  backend/src/main/java/booki_today/persistence/repository/participated_booki/ParticipatedBookiRepositoryImpl.java
Labels: feat

#11 [BE] Persistence Layer 구성 추가
  backend/src/main/java/booki_today/domain/category/CategoryType.java
  backend/src/main/java/booki_today/domain/member/LoginType.java
  backend/src/main/java/booki_today/persistence/entity/BaseTimeEntity.java
  backend/src/main/java/booki_today/persistence/entity/category/CategoryJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/created_booki/CreatedBookiJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/email_certification_number/EmailCertificationNumberJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/invitation_link/InvitationLinkJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/member/MemberJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/participated_booki/ParticipatedBookiJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/university/UniversityJpaEntity.java
  backend/src/main/java/booki_today/persistence/repository/category/CategoryJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/CategoryRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/CategoryRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/email_certification_number/EmailCertificationJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/email_certification_number/EmailCertificationNumberRepository.java
  backend/src/main/java/booki_today/persistence/repository/email_certification_number/EmailCertificationNumberRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/university/UniversityJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/university/UniversityRepository.java
  backend/src/main/java/booki_today/persistence/repository/university/UniversityRepositoryImpl.java
Labels: feat

#18 [BE] Persistence Layer 구성 추가
  backend/src/main/java/booki_today/persistence/entity/clan/clan/ClanJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/clan/clan_member/ClanMemberJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/clan/clan_member_candidate/ClanMemberCandidateJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/custom_filter/custom_filter/CustomFilterJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/custom_filter/custom_filter_status/CustomFilterStatusJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/department/DepartmentJpaEntity.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan/ClanJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan/ClanRepository.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan/ClanRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan_member/ClanMemberJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan_member/ClanMemberRepository.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan_member/ClanMemberRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan_member_candidate/ClanMemberCandidateJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan_member_candidate/ClanMemberCandidateRepository.java
  backend/src/main/java/booki_today/persistence/repository/clan/clan_member_candidate/ClanMemberCandidateRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/custom_filter/custom_filter/CustomFilterJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/custom_filter/custom_filter/CustomFilterRepository.java
  backend/src/main/java/booki_today/persistence/repository/custom_filter/custom_filter/CustomFilterRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/custom_filter/custom_filter_status/CustomFilterStatusJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/custom_filter/custom_filter_status/CustomFilterStatusRepository.java
  backend/src/main/java/booki_today/persistence/repository/custom_filter/custom_filter_status/CustomFilterStatusRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/department/DepartmentJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/department/DepartmentRepository.java
  backend/src/main/java/booki_today/persistence/repository/department/DepartmentRepositoryImpl.java
Labels: feat⚙️

#22 [BE] Controller 테스트 페이크 객체 사용하는 방식으로 변경
  backend/src/test/java/booki_today/util/ControllerTest.java
Labels: feat⚙️

#23 [BE] : 아마존 S3 및 SES 관련 파일 업로드 삭제 메일 전송 기능 구현
  backend/build.gradle
  backend/src/main/java/booki_today/application/file/AmazonS3Service.java
  backend/src/main/java/booki_today/application/file/FileService.java
  backend/src/main/java/booki_today/application/mail/AmazonSesService.java
  backend/src/main/java/booki_today/application/mail/MailService.java
  backend/src/main/java/booki_today/dto/file/FileAddRequest.java
  backend/src/main/java/booki_today/dto/file/FileDeleteRequest.java
  backend/src/main/java/booki_today/dto/file/FileInfoResponse.java
  backend/src/main/java/booki_today/dto/mail/MailSendRequest.java
  backend/src/main/java/booki_today/global/annotation/Implement.java
  backend/src/main/java/booki_today/global/config/AwsConfig.java
  backend/src/main/java/booki_today/global/constant/FileExceptionConstant.java
  backend/src/main/java/booki_today/global/constant/MailExceptionConstant.java
  backend/src/main/java/booki_today/implement/file/FileRemover.java
  backend/src/main/java/booki_today/implement/file/FileUploader.java
  backend/src/main/java/booki_today/implement/mail/MailSender.java
  backend/src/main/java/booki_today/presentation/file/FileController.java
  backend/src/main/java/booki_today/presentation/mail/MailController.java
  backend/src/main/resources/templates/authenticationMail.html
  backend/src/test/java/booki_today/fake_class/FakeFileService.java
  backend/src/test/java/booki_today/implement/mail/MailSenderTest.java
  backend/src/test/java/booki_today/presentation/file/FileControllerTest.java
Labels: feat⚙️

#24 [BE] Persistence Layer 구성 변경
  backend/src/main/java/booki_today/domain/assemble/AssembleType.java
  backend/src/main/java/booki_today/domain/category/CategoryType.java
  backend/src/main/java/booki_today/domain/created_booki/BookiType.java
  backend/src/main/java/booki_today/domain/participated_assemble/ParticipatedStatus.java
  backend/src/main/java/booki_today/persistence/entity/assemble/assemble/AssembleJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/assemble/participated_assemble/ParticipatedAssembleJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/category/category/CategoryJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/category/clan_category/ClanCategoryJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/category/department_category/DepartmentCategoryJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/category/university_category/UniversityCategoryJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/created_booki/CreatedBookiJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/email_certification_number/EmailCertificationNumberJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/invitation_link/InvitationLinkJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/member/MemberJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/participated_booki/ParticipatedBookiJpaEntity.java
  backend/src/main/java/booki_today/persistence/entity/university/UniversityJpaEntity.java
  backend/src/main/java/booki_today/persistence/repository/assemble/assemble/AssembleJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/assemble/assemble/AssembleRepository.java
  backend/src/main/java/booki_today/persistence/repository/assemble/assemble/AssembleRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/assemble/participated_assemble/ParticipatedAssembleJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/assemble/participated_assemble/ParticipatedAssembleRepository.java
  backend/src/main/java/booki_today/persistence/repository/assemble/participated_assemble/ParticipatedAssembleRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/category/CategoryRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/category/CategoryJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/category/CategoryRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/category/CategoryRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/category/clan_category/ClanCategoryJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/clan_category/ClanCategoryRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/clan_category/ClanCategoryRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/category/department_category/DepartmentCategoryJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/department_category/DepartmentCategoryRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/department_category/DepartmentCategoryRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/category/university_category/UniversityCategoryJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/university_category/UniversityCategoryRepository.java
  backend/src/main/java/booki_today/persistence/repository/category/university_category/UniversityCategoryRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/created_booki/CreatedBookiJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/created_booki/CreatedBookiRepository.java
  backend/src/main/java/booki_today/persistence/repository/created_booki/CreatedBookiRepositoryImpl.java
  backend/src/main/java/booki_today/persistence/repository/participated_booki/ParticipatedBookiJpaRepository.java
  backend/src/main/java/booki_today/persistence/repository/participated_booki/ParticipatedBookiRepository.java
  backend/src/main/java/booki_today/persistence/repository/participated_booki/ParticipatedBookiRepositoryImpl.java
  backend/src/test/java/booki_today/util/ControllerTest.java
Labels: feat⚙️
